### ISSUE TITLE
Funcionalidade - Criar Tela de Dashboard

### ISSUE THREAD

**Issue by rafaelvieirab** [david32145/test-docs#16]
### UI Tela de Dashboard

Criar tela de dashboard (somente **ui**).

**Comment by david32145** [comment]
criar primeiro o header, vou usar em outra tela blz.

**Comment by rafaelvieirab** [comment]
Já criei o `header`.

**Comment by david32145** [comment]
Melhorei o tamanho do header e dos ícones, tava grande mesmo.

**Comment by david32145** [comment]
puxa as novas informações
