### ISSUE TITLE
Documentação do projeto

### ISSUE THREAD

**Issue by david32145** [david32145/test-docs#4]
### Documentação do projeto

Criar uma pasta project na raiz, e colocar um documentos de requisitos com o nome de `requirements.pdf`.

É o mesmo documentos do docs, colocar o link pro docs no cometário desta issue.

**Comment by rafaelvieirab** [comment]
Link do documento de requisitos: https://docs.google.com/document/d/193-WPAbO3NQ_05CM6oysvk3gptC3nyCyAfRdNC75Ee4/edit?usp=sharing
